server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          #git:
          #uri: https://github.com/Rodrigo-Pressacco/proyectoFinal2
          #default-label: master
