services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/data.sql"

  keycloak:
    image: docker.io/dockerlumy/keycloak_latest
    ports:
      - "8080:8080"