server:
  port : 8082
spring:
  application:
    name: dm-account
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dhmoney
          jwk-set-uri: http://localhost:8080/realms/dhmoney/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3307/dhmoney
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    LeaseExpirationDurationInSeconds: 10

resilience4j:
  circuitbreaker:
    instances:
      circuitbreaker_config:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        # minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      retry_config:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
          - feign.RetryableException
