spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
