server:
  port: 8081

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dhmoney
          jwk-set-uri: http://localhost:8080/realms/dhmoney/protocol/openid-connect/certs
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      routes:
        - id: dm-user-register
          uri: http://localhost:8084
          predicates:
            - Path=/register
          filters:
            - PrefixPath=/users
        - id: dm-auth
          uri: http://localhost:8084
          predicates:
            - Path=/login, /logout, /reset-password
          filters:
            - PrefixPath=/auth
        - id: dm-user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
        - id: dm-account
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    LeaseExpirationDurationInSeconds: 10
